### PR TITLE
reason-react-native-template: template for react-native@0.60.0

### LINKED ISSUE #570: Template not working with latest React Native CLI
Got error when running `npx react-native init ReasonmlDemo --template reason`

```reason
DEMOS npx react-native init ReasonmlDemo --template reason

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn Once Write Anywhere

✔ Downloading template
✖ Copying template
error Error: Cannot find module '/var/folders/dz/xzttny_14gs2lgxcvl5lm5680000gn/T/rncli-init-template-fWzoC3/node_modules/reason/template.config'
Require stack:
- /Users/prisc_000/.npm/_npx/47740/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/template.js
- /Users/prisc_000/.npm/_npx/47740/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/init.js
- /Users/prisc_000/.npm/_npx/47740/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/index.js
- /Users/prisc_000/.npm/_npx/47740/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/prisc_000/.npm/_npx/47740/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/cliEntry.js
- /Users/prisc_000/.npm/_npx/47740/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js
- /Users/prisc_000/.npm/_npx/47740/lib/node_modules/react-native/cli.js
```

### PR DESCRIPTION
**Pull request by MoOx**
I followed https://github.com/react-native-community/cli/blob/master/docs/init.md

Note that the template package is now `reason-react-native-template` instead of `react-native-template-reason` (I will deprecated this one)

Nice part: we can now start the template as a normal React Native app, no shitty workflow needed anymore. Just go into it & `yarn ios` (or android) & tada!

## Try it

Released as `0.1.0`(beta) on npm so you can start trying it asap. If that's ok, I will merge this & released as stable in a few.

```console
react-native init MyApp --template reason-react-native-template
cd MyApp
yarn re:build
yarn ios
```

### ⚠️ Requires `react-native-community/cli@2.3.0` +

In case you got an error saying it's looking for `react-native-template-reason-react-native-template`, be sure to have uninstalled any previous react-native-cli version & install latest community version

```console
npm -g uninstall react-native
npm -g uninstall react-native-cli
yarn global remove react-native
yarn global remove react-native-cli
yarn global add @react-native-community/cli
```

Kapture 2019-08-13 at 22 53 01

Closes #570

### CODE REVIEW

**Comment by idkjs** [comment]
Getting `TeamId` build error.

I am aware of the legacy build system fix(hack?). Is there another way?

```
MooxApp yarn ios
yarn run v1.17.3
warning ../../../package.json: No license field
$ react-native run-ios
info Found Xcode workspace "MooxApp.xcworkspace"
info Building (using "xcodebuild -workspace MooxApp.xcworkspace -configuration Debug -scheme MooxApp -destination id=7AF1F4EF-1B4F-4132-9938-51FB8FB821CB -derivedDataPath build/MooxApp")
................................
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MooxApp.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/prisc_000/working/DEMOS/MooxApp/ios/build/MooxApp

note: Using new build system
note: Planning build
note: Using build description from disk
Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxAppTests/Pods-MooxAppTests.debug.xcconfig: unable to open file (in target "MooxAppTests" in project "MooxApp") (in target 'MooxAppTests')

Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxApp/Pods-MooxApp.debug.xcconfig: unable to open file (in target "MooxApp" in project "MooxApp") (in target 'MooxApp')

Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxAppTests/Pods-MooxAppTests.debug.xcconfig: unable to open file (in target "MooxAppTests" in project "MooxApp") (in target 'MooxAppTests')

Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxApp/Pods-MooxApp.debug.xcconfig: unable to open file (in target "MooxApp" in project "MooxApp") (in target 'MooxApp')

Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxAppTests/Pods-MooxAppTests.debug.xcconfig: unable to open file (in target "MooxAppTests" in project "MooxApp") (in target 'MooxAppTests')

Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxApp/Pods-MooxApp.debug.xcconfig: unable to open file (in target "MooxApp" in project "MooxApp") (in target 'MooxApp')

Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxAppTests/Pods-MooxAppTests.debug.xcconfig: unable to open file (in target "MooxAppTests" in project "MooxApp") (in target 'MooxAppTests')

Build system information
error: /Users/prisc_000/working/DEMOS/MooxApp/ios/Pods/Target Support Files/Pods-MooxApp/Pods-MooxApp.debug.xcconfig: unable to open file (in target "MooxApp" in project "MooxApp") (in target 'MooxApp')

Build system information
warning: Capabilities for MooxApp may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'MooxApp')


** BUILD FAILED **


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  MooxApp
```

**Comment by idkjs** [comment]
This seemed to help: `cd ios && pod install`
```
MooxApp cd ios
➜  ios pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native/`
Fetching podspec for `React-Core` from `../node_modules/react-native/React`
Fetching podspec for `React-DevSupport` from `../node_modules/react-native/React`
Fetching podspec for `React-RCTActionSheet` from `../node_modules/react-native/Libraries/ActionSheetIOS`
Fetching podspec for `React-RCTAnimation` from `../node_modules/react-native/Libraries/NativeAnimation`
Fetching podspec for `React-RCTBlob` from `../node_modules/react-native/Libraries/Blob`
Fetching podspec for `React-RCTImage` from `../node_modules/react-native/Libraries/Image`
Fetching podspec for `React-RCTLinking` from `../node_modules/react-native/Libraries/LinkingIOS`
Fetching podspec for `React-RCTNetwork` from `../node_modules/react-native/Libraries/Network`
Fetching podspec for `React-RCTSettings` from `../node_modules/react-native/Libraries/Settings`
Fetching podspec for `React-RCTText` from `../node_modules/react-native/Libraries/Text`
Fetching podspec for `React-RCTVibration` from `../node_modules/react-native/Libraries/Vibration`
Fetching podspec for `React-RCTWebSocket` from `../node_modules/react-native/Libraries/WebSocket`
Fetching podspec for `React-cxxreact` from `../node_modules/react-native/ReactCommon/cxxreact`
Fetching podspec for `React-jsi` from `../node_modules/react-native/ReactCommon/jsi`
Fetching podspec for `React-jsiexecutor` from `../node_modules/react-native/ReactCommon/jsiexecutor`
Fetching podspec for `React-jsinspector` from `../node_modules/react-native/ReactCommon/jsinspector`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing Folly (2018.10.22.00)
Installing React (0.60.5)
Installing React-Core (0.60.5)
Installing React-DevSupport (0.60.5)
Installing React-RCTActionSheet (0.60.5)
Installing React-RCTAnimation (0.60.5)
Installing React-RCTBlob (0.60.5)
Installing React-RCTImage (0.60.5)
Installing React-RCTLinking (0.60.5)
Installing React-RCTNetwork (0.60.5)
Installing React-RCTSettings (0.60.5)
Installing React-RCTText (0.60.5)
Installing React-RCTVibration (0.60.5)
Installing React-RCTWebSocket (0.60.5)
Installing React-cxxreact (0.60.5)
Installing React-jsi (0.60.5)
Installing React-jsiexecutor (0.60.5)
Installing React-jsinspector (0.60.5)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing yoga (0.60.5.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 21 dependencies from the Podfile and 22 total pods installed.
➜  ios cd ..
➜  MooxA
```

**Comment by MoOx** [comment]
@idk Yeah `pod install` is normally done if you actually use the template via the new RN cli :)

**Comment by MoOx** [comment]
Tested on iOS & android, should be all good by now

**Comment by idkjs** [comment]
`npx react-native init MooxApp --template reason-react-native-template` works with no `pod install`. Probably ran it another way before. Thanks.

**Comment by kelset** [comment]
Hey @MoOx super quick feedback, you don't need to run `yarn global add @react-native-community/cli` (only uninstall the 'old versions') - you should always use the `npx` version of the command (I just tried and if I installed it locally for some reason it was failing).

**Comment by MoOx** [comment]
Thanks for the feedback. Yeah that works indeed. I was not a fan of npx since this tool seems to download all the time the tool, & for slow connection that clearly not ideal. But it seems npx currently doesn't actually download if you already got it. But I am curious: how the update works?

**Comment by kelset** [comment]
> I was not a fan of npx
yeah, same. But I talked with the folks maintaining it and they suggested that - also, if I install it locally, for some reason the init command fails on me 😓

> But I am curious: how the update works?
which update? 🤔

**Comment by MoOx** [comment]
> which update? 🤔

Updating the package used by npx (here: react-native). How does npx know you need to get latest version etc? It doesn't, so it download everytime all metadata...

After uninstalling `@react-native-community/cli`, I tried to run `npx react-native lol` twice & this downloaded the tool once...
But it took 30s to tell me `error Unrecognized command "lol".` (30s twice).

If you don't have the tool installed (which seems to not be recommended if I understand correctly), it will download ENTIRE latest stable react-native to hit a single command from a tiny dependency (compared to entire RN package), definitely not a fan of this approach, but that probably just me being eco 🙃.

But I guess I should document the official recommended way...

**Comment by kelset** [comment]
Oh I see - I don't know much tbh, I just tried on my machine and asked to the team what's the recommended approach.

But we can ask @thymikee for details tbh, I sure he would be able to explain

**Comment by thymikee** [comment]
@MoOx I get your pain. The topic is a bit more complex than one may think, but not getting into details, here's what we're doing (we're in a transition period):

- we want to discourage usage of `react-native-cli` because it's unmaintained and its init implementation is convoluted and split between 2 packages in a weird way, which makes it very hard to develop and test
- we can't deprecate it too quickly because a lot of books, tutorials and learning materials use it and we don't want to make them obsolete too quickly
- we created new init entirely inside `@react-native-community/cli` to mitigate these issues
- we made `react-native` a binary, so that people can opt-out of installing a global package
- we currently promote using `npx` for `init` because of that, but ideally we'd like to recommend `yarn dlx` (coming in v2) which will use global cache (hope that `npx` catches up on caching globals as well) – which should speed up pre-init logic and deps installation
- somewhere in the middle of next year, once global `react-native-cli` init is barely used in the wild, we want to rewrite this package to be a direct proxy to `@react-native-community/cli` and offer users a choice – install a global package or use `npx`/`yarn dlx`, which will run the CLI the same way.

If for some reasons one tends to init new packages very often, they can use the `@react-native-community/cli` directly – be it global, local or built from source. But it's not recommended for a typical user who would likely init RN app twice a year or so.

**Comment by MoOx** [comment]
Thanks for the explanation. I just updated info in c824274

**Pull request merged**
