### PR TITLE
Update README.md for Reason Conf

### PR DESCRIPTION
**Pull request by dylanirlbeck**
@peterpme

### CODE REVIEW

**Comment by MoOx** [comment]
Could you give an explanation about the motivation to put this at this specific location?
I am not against it but you could at least say something about it...

**Comment by dylanirlbeck** [comment]
Hey!

I'd like to do my part of spreading the word about Reason Conf and thought that this would be a great way to show it! I'm a huge fan of your reason-react-native and was hoping you'd be open to it!

Thank you :relaxed:

**Comment by MoOx** [comment]
Not a fan of the idea of a message at the very top of the ready. Maybe instead we could add a message on the homepage of the website?

@cknitt @sgny any thoughts?

**Comment by cknitt** [comment]
Fine with me to add it on the website!

**Comment by MoOx** [comment]
I have updated the thing just a little, will go with that.

**Pull request merged**
